[theme]
base = "light"
primaryColor = "#304b40"
backgroundColor = "#f6f5f2"
secondaryBackgroundColor = "#eaece7"
textColor = "#29332c"
font = "sans serif"

[server]
maxUploadSize = 15

[browser]
gatherUsageStats = false
